# Read-only preflight. Never sources analysis/configuration, installs, or downloads.
cat("R version:", as.character(getRversion()), "\n")
if (getRversion() != "4.5.1") warning("Historical execution used R 4.5.1; current version differs.")
root <- normalizePath(Sys.getenv("CKM_REPO_ROOT", unset = getwd()), winslash = "/", mustWork = TRUE)
required_scripts <- c("R/00_CKM_refactored_config.R", "R/01_CKM_refactored_analysis_v7_methodlock.R", "R/02_CKM_tables_figures_highimpact_v19_reconciled.R", "R/03_CKM_supplementary_tables_S1_S26_v8_reconciled.R", "R/07a_nhanes_download_harmonize.R", "R/07b_nhanes_revised_prevent_ckm_qc.R", "scripts/Stage7_5_Final_Figure_Supplement_Production.R")
stopifnot(all(file.exists(file.path(root, required_scripts))))
cat("Required scripts: PASS\n")
packages <- c("survey", "rms", "pROC", "caret", "recipes", "gbm", "randomForest", "glmnet", "fastshap", "haven", "dplyr", "tidyr", "purrr", "stringr", "tibble", "readr", "preventr", "nhanesA", "readxl", "tidyselect", "PRROC", "broom", "kernlab", "kknn", "ggplot2", "officer", "flextable", "patchwork", "scales")
ip <- installed.packages()
for (p in packages) cat("Package:", p, if (p %in% rownames(ip)) ip[p, "Version"] else "MISSING", "\n")
for (d in c("R", "scripts", "documentation", "manifests", "sessionInfo")) cat("Release directory:", d, dir.exists(file.path(root, d)), "\n")
for (d in c("data/public/nhanes", "restricted_data/china", "results")) cat("Runtime directory:", d, dir.exists(file.path(root, d)), "(not created by preflight)\n")
cross <- Sys.getenv("CKM_CHINA_CROSS_FILE", unset = file.path(root, "restricted_data/china/cross_filtered.xlsx"))
long <- Sys.getenv("CKM_CHINA_LONG_FILE", unset = file.path(root, "restricted_data/china/suifang.xlsx"))
cat("Restricted input presence: cross", file.exists(cross), "repeated", file.exists(long), "\n")
cat("Full final analysis requires controlled Chinese inputs. Public acquisition/construction can run separately.\n")
